// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DCTLINPUT_DCTL_H_
#define FLATBUFFERS_GENERATED_DCTLINPUT_DCTL_H_

#include "flatbuffers/flatbuffers.h"

namespace DCTL {

struct Input;
struct InputBuilder;

struct Input FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef InputBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQUENCE = 4,
    VT_PLAYER_ID = 6,
    VT_LEFT = 8,
    VT_RIGHT = 10,
    VT_UP = 12,
    VT_DOWN = 14
  };
  uint32_t sequence() const {
    return GetField<uint32_t>(VT_SEQUENCE, 0);
  }
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  bool left() const {
    return GetField<uint8_t>(VT_LEFT, 0) != 0;
  }
  bool right() const {
    return GetField<uint8_t>(VT_RIGHT, 0) != 0;
  }
  bool up() const {
    return GetField<uint8_t>(VT_UP, 0) != 0;
  }
  bool down() const {
    return GetField<uint8_t>(VT_DOWN, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SEQUENCE) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID) &&
           VerifyField<uint8_t>(verifier, VT_LEFT) &&
           VerifyField<uint8_t>(verifier, VT_RIGHT) &&
           VerifyField<uint8_t>(verifier, VT_UP) &&
           VerifyField<uint8_t>(verifier, VT_DOWN) &&
           verifier.EndTable();
  }
};

struct InputBuilder {
  typedef Input Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_sequence(uint32_t sequence) {
    fbb_.AddElement<uint32_t>(Input::VT_SEQUENCE, sequence, 0);
  }
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(Input::VT_PLAYER_ID, player_id, 0);
  }
  void add_left(bool left) {
    fbb_.AddElement<uint8_t>(Input::VT_LEFT, static_cast<uint8_t>(left), 0);
  }
  void add_right(bool right) {
    fbb_.AddElement<uint8_t>(Input::VT_RIGHT, static_cast<uint8_t>(right), 0);
  }
  void add_up(bool up) {
    fbb_.AddElement<uint8_t>(Input::VT_UP, static_cast<uint8_t>(up), 0);
  }
  void add_down(bool down) {
    fbb_.AddElement<uint8_t>(Input::VT_DOWN, static_cast<uint8_t>(down), 0);
  }
  explicit InputBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Input> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Input>(end);
    return o;
  }
};

inline flatbuffers::Offset<Input> CreateInput(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t sequence = 0,
    uint32_t player_id = 0,
    bool left = false,
    bool right = false,
    bool up = false,
    bool down = false) {
  InputBuilder builder_(_fbb);
  builder_.add_player_id(player_id);
  builder_.add_sequence(sequence);
  builder_.add_down(down);
  builder_.add_up(up);
  builder_.add_right(right);
  builder_.add_left(left);
  return builder_.Finish();
}

inline const DCTL::Input *GetInput(const void *buf) {
  return flatbuffers::GetRoot<DCTL::Input>(buf);
}

inline const DCTL::Input *GetSizePrefixedInput(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<DCTL::Input>(buf);
}

inline bool VerifyInputBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<DCTL::Input>(nullptr);
}

inline bool VerifySizePrefixedInputBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<DCTL::Input>(nullptr);
}

inline void FinishInputBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<DCTL::Input> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedInputBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<DCTL::Input> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace DCTL

#endif  // FLATBUFFERS_GENERATED_DCTLINPUT_DCTL_H_
