// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DCTLINPUTACK_DCTL_H_
#define FLATBUFFERS_GENERATED_DCTLINPUTACK_DCTL_H_

#include "flatbuffers/flatbuffers.h"

namespace DCTL {

struct InputAck;
struct InputAckBuilder;

struct InputAck FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef InputAckBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQUENCE = 4,
    VT_PLAYER_ID = 6
  };
  uint32_t sequence() const {
    return GetField<uint32_t>(VT_SEQUENCE, 0);
  }
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SEQUENCE) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID) &&
           verifier.EndTable();
  }
};

struct InputAckBuilder {
  typedef InputAck Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_sequence(uint32_t sequence) {
    fbb_.AddElement<uint32_t>(InputAck::VT_SEQUENCE, sequence, 0);
  }
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(InputAck::VT_PLAYER_ID, player_id, 0);
  }
  explicit InputAckBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<InputAck> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<InputAck>(end);
    return o;
  }
};

inline flatbuffers::Offset<InputAck> CreateInputAck(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t sequence = 0,
    uint32_t player_id = 0) {
  InputAckBuilder builder_(_fbb);
  builder_.add_player_id(player_id);
  builder_.add_sequence(sequence);
  return builder_.Finish();
}

inline const DCTL::InputAck *GetInputAck(const void *buf) {
  return flatbuffers::GetRoot<DCTL::InputAck>(buf);
}

inline const DCTL::InputAck *GetSizePrefixedInputAck(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<DCTL::InputAck>(buf);
}

inline bool VerifyInputAckBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<DCTL::InputAck>(nullptr);
}

inline bool VerifySizePrefixedInputAckBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<DCTL::InputAck>(nullptr);
}

inline void FinishInputAckBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<DCTL::InputAck> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedInputAckBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<DCTL::InputAck> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace DCTL

#endif  // FLATBUFFERS_GENERATED_DCTLINPUTACK_DCTL_H_
